[package]
name = "burst"
version = "0.1.0"
edition = "2024"

[dependencies]
lexer = { path = "../rings/ring0/lexer" }
ast = { path = "../rings/ring0/ast" }
parser = { path = "../rings/ring1/parser" }
elaboration = { path = "../rings/ring2/elaboration" }
command_parser = { path = "../rings/ring0/command_parser" }
